[[remotes]]
git_url = "https://github.com/home-operations/.github"
ref = "main"
configs = ["lefthook.common.toml"]

[pre-commit.commands.droast]
glob = ["**/Dockerfile"]
run = "droast {staged_files}"
