---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request Container Build

on:
  pull_request:
    branches: ["main"]
    paths: ["apps/**"]

permissions:
  contents: read
  packages: write

jobs:
  filter:
    name: Filter
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@2cc35474e9d534ed0d743aa122fd142afbdaa0ad # v0.3.1
        with:
          path: apps
          include_only_directories: true
          max_depth: 1

  prepare:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    name: Prepare (${{ matrix.app }})
    needs: filter
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.prepare.outputs.app }}
      platforms: ${{ steps.prepare.outputs.platforms }}
      version: ${{ steps.prepare.outputs.version }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.filter.outputs.changed-files) }}
      fail-fast: false
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare Container
        id: prepare
        uses: ./.github/actions/container-prepare
        with:
          app: ${{ matrix.app }}

  build:
    name: Build (${{ matrix.app }}-${{ matrix.platform }})
    needs: ["prepare"]
    strategy:
      matrix:
        app: ${{ needs.prepare.outputs.app }}
        version: ${{ needs.prepare.outputs.version }}
        platform: ${{ fromJson(needs.prepare.outputs.platforms) }}
    runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build Container
        id: build
        uses: ./.github/actions/container-build
        with:
          app: ${{ matrix.app }}
          platform: ${{ matrix.platform }}
          release: false
          version: ${{ matrix.version }}

      - name: Test Container
        uses: ./.github/actions/container-tests
        with:
          app: ${{ matrix.app }}
          image: ${{ steps.build.outputs.local-digest }}
          token: ${{ github.token }}

  status:
    if: ${{ !cancelled() }}
    needs: ["filter", "prepare", "build"]
    name: Build Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
